### ISSUE TITLE
Flag values are not changing when configmap is updated

### ISSUE THREAD

**Issue by bseenu** [fortio/dflag#63]
tried manually changing the configmap values, can see the changed values in Flags Debug View ( _/flags_ ) but the app is still serving the old values

Version used : v1.7.1-0.20231104204858-c49706357174

**Comment by ldemailly** [comment]
do you have an example? because if it shows the changes in debug, then doing .Get() on the flag will also get the changed value? is the app forgetting to refetch the current value?

ps: what is  v1.7.1-0.20231104204858-c49706357174 ? should be 1.7.2 (and the struct2env is in ... https://github.com/fortio/struct2env v0.4.1)

**Comment by bseenu** [comment]
Looks like there is logic issue in how we are constructing the object from multiple dflag values, the individual ones are working fine which rules out the issue with the dflag, closing this out. Thanks
